### ISSUE TITLE
System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by asCii88** [Vangos/kinect-2-face-basics#1]
Do you have any idea why am I getting this exception at line 54?

El código de usuario no controló System.Runtime.InteropServices.SEHException
  HResult=-2147467259
  Message=External component has thrown an exception.
  Source=Microsoft.Kinect.Face
  ErrorCode=-2147467259
  StackTrace:
       at Microsoft.Kinect.Face.FaceFrameSource..ctor(KinectSensor sensor, UInt64 initialTrackingId, FaceFrameFeatures initialFaceFrameFeatures)
       at Kinect2FaceBasics_WinRT.MainPage..ctor()
       at Kinect2FaceBasics_WinRT.Kinect2FaceBasics_WinRT_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
       at Kinect2FaceBasics_WinRT.Kinect2FaceBasics_WinRT_XamlTypeInfo.XamlUserType.ActivateInstance()
  InnerException:

**Comment by Vangos** [comment]
Try adding the following line under Project -> Properties -> Build Events -> Post-build event:

xcopy "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0\ExtensionSDKs\Microsoft.Kinect.Face\2.0\Redist\CommonConfiguration\x64\NuiDatabase" "NuiDatabase" /e /y /i /r

**Comment by asCii88** [comment]
Hello, thanks for your answer. I did it. It copied the files, but I sill have the same issue. Well, in fact this very same thing happens every time I try to run any of the Face examples that come with the SDK. Everything else works just fine.

**Comment by Vangos** [comment]
Probably a driver issue. Try to re-install the SDK. Does body tracking work OK?

**Comment by asCii88** [comment]
Everything works OK except for that. Re-installing the SDK made no difference :( I will download it again, just in case.

**Comment by acam16** [comment]
Good afternoorn!
I have a problem with the static resource eyestyle, nosestyle,mouthstyle, the error consist in that the resource could not be resolved.
other error is in the line 71, the error is 'colorframe' does not contain a definition for 'ToBitmap'
thanks.

**Comment by Vangos** [comment]
This is the ToBitmap method:

https://github.com/Vangos/kinect-2-face-basics/blob/master/Kinect2FaceBasics/Kinect2FaceBasics_NET/ColorBitmapGenerator.cs
